# This file is auto-generated and contains the integrals that were answered correctly.
QUESTIONS_CORRECT = [
    'integrate(1/(x**2 - 2*x + 3), x)',
    'integrate(2025/(2023*2024), x)',
    'integrate(x/(x**2024 - 1)/(x**506 - 1), x)',
    'integrate((5*x**3 - 3*x)**2, x)',
    'integrate(exp(-(x-2024)**2/4), x)',
    'integrate(sech(x), x)',
    'integrate((1 + x + x**2 + x**3 + x**4)*(1 - x + x**2 - x**3 + x**4), x)',
    'integrate(x**5, x)',
    'integrate(x + sin(x) + x*cos(x) + sin(x)*cos(x), x)',
    'integrate(sin(x)**6 + cos(x)**6 + 3*sin(x)**2*cos(x)**2, x)',
    'integrate(log(x/pi)/(log(x)**log(pi*E)), x)',
    'integrate(x**5 + 5*x**4 + 10*x**3 + 8*x**2 + x, x)',
    'integrate((arctan(x) + arccot(x))/x, x)',
    'integrate(x**3*sin(x**2), x)',
    'integrate(1/cosh(x)**2, x)',
    'integrate(sin(x + sin(x)) - sin(x - sin(x)), x)',
    'integrate(1/sqrt(x - x**2), x)',
    'integrate(sum(binomial(n + 3, n)*x**n, (n, 0, oo)), x)',
    'integrate(1/(x**2 + (x - 1)**2), x)',
    'integrate(log(x**2 + 1), x)',
    'integrate((2*x + 1)/(2*x**2 + 2*x + 1), x)',
    'integrate(arcsin(x)/x**3, x)',
    'integrate(sin(2*x)*cos(cos(x)), x)',
    'integrate(x*(1 - x)**2020, x)',
    'integrate(exp(x+exp(x)) + exp(x-exp(x)), x)',
    'integrate(cos(x)*cos(2*x)*cos(3*x), x)',
    'integrate(exp(x)*(cos(x)**2 + cos(x)*sin(x) - sin(x)**2), x)',
    'integrate(cos(arctan(x)), x)',
    'integrate((1+sqrt(3))*x, x)',
    'integrate(cos(arctan(x)), x)',
    'integrate(cos(x)*cosh(x) + sin(x)*sinh(x), x)',
    'integrate(sin(cos(sin(x)))*sin(sin(x))*cos(x), x)',
    'integrate(1+sin(x), x)',
    'integrate(tanh(x)**2, x)',
    'integrate((2017*x**2016 + 2018*x**2017)/(4034 + 2*x + 4035 + x + 4036), x)',
    'integrate((1+x**2)**(3/2), x)',
    'integrate(sech(x), x)',
    'integrate(tanh(x), x)',
    'integrate(arcsin(3*x**(1/3)), x)',
    'integrate(blog2(x)*xc, x)',
    'integrate((2*e**(x**2)/(x+1))*cos(x) - (e**(x**2)+x)*sin(x), x)',
    'integrate(sin(sin(x))*cos(sin(x))*cos(x), x)',
    'integrate(x**3/sqrt(x**2+1), x)',
    'integrate(cos(x)**4 - sin(x)**4, x)',
    'integrate(x**2015, x)',
    'integrate(1/sqrt(x**2+25), x)',
    'integrate(sin(2*x)*cos(3*x), x)',
    'integrate(arcsinh(x), x)',
    'integrate(x*arctan(x), x)',
    'integrate(1/(x**2 - 15*x - 2014), x)',
    'integrate((arcsin(x))**2, x)',
    'integrate(6 - 11*x + 6*x**2 - x**3, x)',
    'integrate((log(x)*cos(x) - sin(x)/x)/(log(x)**2), x)',
    'integrate(sin(x)/(1+tan(x)**2), x)',
    'integrate(x/(1+x**2), x)',
    'integrate(1/(2-2*x+x**2), x)',
    'integrate(1/sqrt(1-4*x-x**2), x)',
    'integrate(x-1, x)',
    'integrate(sin(x)/(1+tan(x)**2), x)',
    'integrate(x/(1+x**2), x)',
    'integrate(1/(2-2*x+x**2), x)',
    'integrate(1/sqrt(1-4*x-x**2), x)',
    'integrate(x-1, x)',
    'integrate(sin(x)/(1+tan(x)**2), x)',
    'integrate(x/(1+x**2), x)',
    'integrate(1/(2-2*x+x**2), x)',
]
