# This file is auto-generated and contains the integrals that were answered incorrectly.
QUESTIONS_INCORRECT = [
    'integrate((x - 1)*log(x+1)/(x + 1)/log(x-1), x)',
    'integrate(x*log(x) + 2*x, x)',
    'integrate(1/(x*log(x) + 2*x), x)',
    'integrate(arccos(sin(x)), x)',
    'integrate((cos(x) + cot(x) + csc(x) + 1)/(sin(x) + tan(x) + sec(x) + 1), x)',
    'integrate((sin(x) + cos(x))**11, x)',
    'integrate((sinh(x) + cosh(x))**11, x)',
    'integrate(csc(x)**2 * tan(x)**2024, x)',
    'integrate(cos(x)*(log(cos(x)) - x*tan(x)), x)',
    'integrate((1 - 1/x**2)*exp(x+1/x), x)',
    'integrate((x + 1 - exp(-x))*exp(x*exp(x)), x)',
    'integrate((arctan(x)/(1-x**2) + arctanh(x)/(1+x**2)), x)',
    'integrate(sum(x**(2*n-1012), (n, 0, 2024)), x)',
    'integrate(x**4/(3 - 6*x + 6*x**2 - 4*x**3 + 2*x**4), x)',
    'integrate(x + ContinuedFraction([1, x, 1, x]), x)',
    'integrate(x*log(x), x)',
    'integrate(exp(x)*(1 + exp(x))*log(1 + exp(x)), x)',
    'integrate(sin(x)**2 + cos(x)**2 + tan(x)**2 + cot(x)**2 + sec(x)**2 + csc(x)**2, x)',
    'integrate(floor(2023*sin(x)), x)',
    'integrate((2*log(x) + 1)*exp(log(x)**2), x)',
    'integrate((1 - x)**3 + (x - x**2)**3 + (x**2 - 1)**3 - 3*(1 - x)*(x - x**2)*(x**2 - 1), x)',
    'integrate(Abs(Abs(Abs(Abs(x) - 1) - 1) - 1), x)',
    'integrate((x + E + 1)**x*exp(x), x)',
    'integrate(sqrt(2*x/(x + 1))/(2 - x**2), x)',
    'integrate((1 + 2*x**2022)/(x + x**2023), x)',
    'integrate(3*sin(20*x)*cos(23*x) + 20*sin(43*x), x)',
    'integrate(sin(x)/(2*exp(x) + cos(x) + sin(x)), x)',
    'integrate((1 + cos(x))/(x + sin(x)), x)',
    'integrate(x**2 - floor(x)*ceiling(x), x)',
    'integrate(sinh(x)/(cosh(x) - sinh(x)), x)',
    'integrate(x/(sqrt(x - 1) + sqrt(x + 1)), x)',
    'integrate(cos(x + cos(x)), x)',
    'integrate(x/(1 - x**4), x)',
    'integrate(exp(exp(x)) - exp(exp(x) - x), x)',
    'integrate(Limit(sin(pi/3)*sin(pi/3)*sin(pi/3)*x, n, oo), x)',
    'integrate(sqrt(1 - sqrt(x)), x)',
    'integrate(x**3/(1 + x + x**2/2 + x**3/6), x)',
    'integrate(tan(x)**4*sec(x)**3 + tan(x)**2*sec(x)**5, x)',
    'integrate((1 + log(x))*log(log(x)), x)',
    'integrate(1/(1 + sin(x)) + 1/(1 + cos(x)) + 1/(1 + tan(x)) + 1/(1 + cot(x)) + 1/(1 + sec(x)) + 1/(1 + csc(x)), x)',
    'integrate(1/(1 + cos(x)**2), x)',
    'integrate(log(2*x)/(x*log(x)), x)',
    'integrate(1/(exp(x) + 1), x)',
    'integrate(log(x)*log(log(x))/x, x)',
    'integrate(log((1 + x)/(1 - x)), x)',
    'integrate(sqrt(x*sqrt(x*sqrt(x))), x)',
    'integrate(sin(x)**4*cos(x)**4*(cos(x) + sin(x))*(cos(x) - sin(x)), x)',
    'integrate(cos(x)**(2020), x)',
    'integrate(sin(sin(x) - x), x)',
    'integrate(1/(x - 1) + sum((k + 1)*x**k, (k, 0, 2018))/sum(x**k, (k, 0, 2019)), x)',
    'integrate(1/(tan(x)**(sqrt(2020)) + 1), x)',
    'integrate(sec(x)**4*tan(x)/(sec(x)**4 + 4), x)',
    'integrate(x**2*x/(2*log(x) + 2), x)',
    'integrate(sqrt(1 - x**2), x)',
    'integrate(x**5*exp(-x**4), x)',
    'integrate(tan(cos(x)), x)',
    'integrate((x + 1)/(x*(x + log(x))), x)',
    'integrate(1/(1 - x**2), x)',
    'integrate(2/log(x), x)',
    'integrate((cos(3*x) + sin(2*x))*(-sin(2019*x) + cos(3*x)), x)',
    'integrate(cos(x)*cos(sin(x))*cos(sin(sin(x))), x)',
    'integrate(exp(-2019/(4*t**2))*t**2, x)',
    'integrate(sin(sqrt(x)), x)',
    'integrate(sqrt(x)/(1 + x), x)',
    'integrate(Limit(exp(-x**(2*n)), n, oo), x)',
    'integrate(x/(1*log(x)), x)',
    'integrate((sin(20*x) + sin(19*x))/(cos(20*x) + cos(19*x)), x)',
    'integrate(sin(x)/sin(x + pi/4), x)',
    'integrate(1/(x + sqrt(3)*x), x)',
    'integrate(x/(x**2 + 1)*(2*log(x) + 1), x)',
    'integrate((2*x**3 - 1)/(x*(x**3 + 1)), x)',
    'integrate(tan(cos(x)), (x, 0, 2*pi))',
    'integrate(x*(x + log(x)), x)',
    'integrate(e**(x+e) + e**(x-e), x)',
    'integrate(1 - x**2, (x, -1/2, 1/2))',
    'integrate(2*log(x), (x, 0, 2))',
    'integrate((cos(3*x) + sin(2*x)) * (- sin(2019*x) + cos(3*x)), (x, -2*pi, 2*pi))',
    'integrate(cos(x)*cos(sin(x))*cos(sin(sin(x))), x)',
    'integrate(e**(-2019/(4*t**2))*t**2, (t, 0, oo))',
    'integrate(sin(sqrt(x)), x)',
    'integrate(sqrt(x)/(1+x), (x, 0, 1))',
    'integrate(cos(x)*cos(2*x)*cos(3*x), (x, 0, 2*pi))',
    'Limit(integrate(e**(-x**(2*n)), (x, -oo, oo)), n, oo)',
    'integrate(x*log(x), (x, 0, E))',
    'integrate((sin(20*x)+sin(19*x))/(cos(20*x)+cos(19*x)), (x, 0, pi/100))',
    'integrate(e**x*cos(x)**2 + e**x*cos(x)*sin(x) - e**x*sin(x)**2, x)',
    'integrate(sin(x)/sin(x+pi/4), (x, 0, pi/2))',
    'integrate(x/(x**2+1)*(2*log(x)+1), (x, 0, 2))',
    'integrate((2*x**3 - 1)/(x*(x**3+1)), x)',
    'integrate(e**x + e**(x+2), x)',
    'integrate(s*x**3 * r*x**4 * q*x*sqrt(5)*x, x)',
    'integrate(Abs(sin(2018*x)), (x, 0, 2018*pi))',
    'integrate(tan(x)+cot(x), x)',
    'integrate(x**5/(2+x**12), x)',
    'integrate(e**x + cos(x)*e**x + sin(x)*e**x, x)',
    'integrate(cos(x)/(1-cos(2*x)), x)',
    'integrate(e**x*(1/x+log(x)), x)',
    'integrate((sin(2*x)-sin(2*x))/(cos(2*x)-cos(2*x), x)',
    'integrate(x**25/(25*x**16 + 25 + x**9/25), x)',
    'integrate(cos(x)/(2-cos(x)**2), (x, 0, pi/2))',
    'integrate(p*x*sqrt(x) - x**2, x)',
    'integrate((x-1)/(x+x**2*log(x)), x)',
    'integrate(csc(x)*sec(x), x)',
    'integrate(x**2/sqrt(x**3+2), x)',
    'integrate(log(x)/x**2, (x, 1, oo))',
    'integrate(x**3/(e*x**2), x)',
    'integrate(1/(x*sqrt(x**2-1)), (x, 1, 2))',
    'integrate(1/(x*(x**2+1)), (x, 1, oo))',
    'integrate(acosh(x), x)',
    'integrate(e**(-2*x**2-5*x-3), (x, -oo, oo))',
    'integrate(sin(sqrt(x)), x)',
    'integrate(1/(x+1/x)**2, (x, 0, oo))',
    'integrate((2+x)*e**(-x)/x**3, x)',
    'integrate(p*x*(1-x), x)',
    'integrate(tanh(x)*exp(x), x)',
    'integrate(p*sin(x)+1, (x, 0, pi/2))',
    'Limit(In, n, oo)',
    'integrate(sin(x+pi/4)**2*e**(x**2), (x, -oo, oo))',
    'integrate(3*x**2/(x**3+1)**2 * e**(-x**(6-2*x**3)), (x, -oo, oo))',
    'integrate(1/(1+tan(x)**2017), (x, 0, pi/2))',
    'integrate(e**(2*x)*cos(3*x), x)',
    'integrate(cos(x)*(cos(x)+1)*tan(x)*(1+log(cos(x))), x)',
    'integrate(Abs(x**3 - x), (x, -4, 4))',
    'integrate(log(sqrt(x)), x)',
    'integrate(e**(x+e) - e**(x-e), x)',
    'integrate(log(log(x))/(x*log(x)), x)',
    'integrate(1/(1+tan(x)**2), (x, 0, pi/3))',
    'integrate(e**x*cos(x) - e**x*sin(x), x)',
    'integrate(x**3*e**(-x**2), (x, 0, oo))',
    'integrate((1+sqrt(x)+x**(1/3))*(1+x**(-1/2)+x**(-1/3)), x)',
    'integrate((cos(x)+sin(x))/x**2 + (sin(x)-cos(x))/x, x)',
    'integrate(x/(x**4+x**2+1), x)',
    'integrate(e**(2016*x+6048*x), x)',
    'integrate((1-cos(x))/sin(x), (x, pi/3, pi/2))',
    'integrate(1/(1-x+x**2-x**3), x)',
    'integrate(1/(2+cosh(x)), (x, 0, oo))',
    'integrate(x/sqrt(2+4*x), x)',
    'integrate(cos(sqrt(x))/sqrt(x), (x, 0, 8))',
    'integrate(sec(x), x)',
    'integrate(e**(sin(x))*tan(x)*csc(x), (x, 0, pi/2))',
    'integrate(x*(log(x))**2, (x, 1, e))',
    'integrate(1/(5 + 4*sqrt(x) + x), x)',
    'integrate(x/((x-3)*(x+5)**2), (x, 0, 2))',
    'integrate(log(1+log(x))/x, x)',
    'integrate(sqrt(csc(x) - sin(x)), x)',
    'integrate((log(x,2) - 1/(x*log(x,2))), (x, 2, e))',
    'integrate(arctan(e**x)/e**(3*x), x)',
    'integrate(Abs(x-1)/(Abs(x-2)+Abs(x-3)), (x, 0, 4))',
    'integrate(1/(sin(x)**4+cos(x)**4), (x, 0, 2*pi))',
    'integrate((1+e**x)/(1-e**x), x)',
    'integrate(tan(x)**4, x)',
    'integrate(sin(x)*tan(x)**2, x)',
    'integrate((x+1)/(x**2+2*x+3), x)',
    'integrate(log(x**2), (x, 1, e))',
    'integrate(sin(sqrt(3)*x), (x, -9, 9))',
    'integrate(diff(h(e**(1+x-x**2)), x), (x, 0, oo))',
    'integrate(r*x + q*x + sqrt(x), (x, 0, 2))',
    'integrate(sqrt(x)*e**(sqrt(x)), x)',
    'integrate(Abs(1+2*sin(x)), (x, 0, 2*pi))',
    'integrate(x*(1-x)**2014, x)',
    'integrate(x**2/(x-1), (x, -1, 0))',
    'integrate(e**x*log(1+x**2) - 2*(1+x)*arctan(x), x)',
    'integrate(sqrt(x**2-1)/x, x)',
    'integrate(x*sec(4*x)**2, x)',
    'integrate(1/(b1 - log(1-x,2)), (x, 0, 1))',
    'integrate(q*x + p*x**2 + 1, (x, 0, 1/sqrt(3)))',
    'integrate(2+cos(x), (x, 0, 5*pi/2))',
    'integrate(log(x**2) - 2*log(2*x), x)',
    'integrate(e**(Abs(x)), (x, -1, 3))',
    'integrate(x**3 - 3*x**2 + 3*x - 1, (x, 1, 11))',
    'integrate(12 - 3*x**2, (x, 0, 2))',
    'integrate(x + (x-3)/(7+sin(x-3)), (x, 0, 6))',
    'integrate((x**5 - x**3 + x**2 - 1)/(x**4 - x**3 + x - 1), x)',
    'integrate(log(x), (x, 0, 1))',
    'integrate(1 - e**(-x), x)',
    'integrate(sin(x)**2*cos(x)**2, (x, 0, pi))',
    'integrate(pi*sin(pi*sqrt(x))/sqrt(x), (x, 0, 441))',
    'integrate(tan(x)**2, x)',
    'integrate((x - b)**2, (x, 0, 256))',
    'integrate(e**(2*sqrt(x)), x)',
    'integrate(cos(x)*cot(x), x)',
    'integrate(2*log(x) + log(x)**2, x)',
    'integrate(sin(x)*log(sin(x)), x)',
    'integrate(x/(1-x**4), x)',
    'integrate(sec(x)**5*tan(x)**3, x)',
    'integrate(1/(1-sin(x)), (x, -pi/4, pi/4))',
    'integrate(x/sqrt(x**2-2), x)',
    'integrate(1/(x-1), x)',
    'integrate(x**(1/4)*log(x), x)',
    'integrate((1+sqrt(x))/(sqrt(x)-x**2), x)',
    'integrate(1/sqrt(x*(sqrt(4*x)+1)**10), x)',
    'integrate(sin(acos(x)), (x, 0, 1))',
    'integrate(log(1/x), (x, 1/4, 1/2))',
    'integrate(1/(1+sin(x)), (x, 0, pi/2))',
    'integrate(sqrt(x)/(sqrt(2012-x)+sqrt(x)), (x, 1, 2011))',
    'integrate((x-1)/((x+1)*sqrt(x**3+x**2+x)), x)',
    'integrate((x**4+4*x**3+6*x**2+4*x+1)/(x**3-3*x**2+3*x-1), (x, -1, 0))',
    'integrate((cos(x)*log(x)+sin(x))/x, x)',
    'integrate(1/(x**3-x), x)',
    'integrate(x*asin(x)/sqrt(1-x**2), (x, 0, 1/2))',
    'integrate(x*(1-x)**99, (x, 0, 1))',
    'integrate(sin(4*x)/sin(x), (x, 0, pi/2))',
    'integrate((x-1)**2/(1+x**(1/3)), x)',
    'integrate(sqrt(2*x**2-1), x)',
    'integrate(sqrt(e**x-1), x)',
    'integrate(x/(x**4+4), x)',
    'integrate((cos(x)-sin(x))**2, (x, 0, 2))',
    'integrate(x*cosh(x)/sinh(x)**2, x)',
    'integrate(x**5/sqrt(1+x**3), (x, 0, 2))',
    'integrate((x**7-1)*log(x), (x, 0, 1))',
    'integrate(log(x**2) - 2*log(2*x), x)',
    'integrate(e**(Abs(x)), (x, -1, 3))',
    'integrate((log(x)*cos(x)-sin(x)/x)/(log(x)**2), x)',
    'integrate(x**3-3*x**2+3*x-1, (x, 1, 11))',
    'integrate(12-3*x**2, (x, 0, 2))',
    'integrate(x+(x-3)/(7+sin(x-3)), (x, 0, 6))',
    'integrate((x**5-x**3+x**2-1)/(x**4-x**3+x-1), x)',
    'integrate(log(x), (x, 0, 1))',
    'integrate(1-e**(-x), x)',
    'integrate(sin(x)**2*cos(x)**2, (x, 0, pi))',
    'integrate(pi*sin(pi*sqrt(x))/sqrt(x), (x, 0, 441))',
    'integrate(tan(x)**2, x)',
    'integrate((x-b)**2, (x, 0, 256))',
    'integrate(e**(2*sqrt(x)), x)',
    'integrate(cos(x)*cot(x), x)',
    'integrate(2*log(x)+log(x)**2, x)',
    'integrate(sin(x)*log(sin(x)), x)',
    'integrate(x/(1-x**4), x)',
    'integrate(sec(x)**5*tan(x)**3, x)',
    'integrate(1/(1-sin(x)), (x, -pi/4, pi/4))',
    'integrate(x/sqrt(x**2-2), x)',
    'integrate(1/(x-1), x)',
    'integrate(x**(1/4)*log(x), x)',
    'integrate((1+sqrt(x))/(sqrt(x)-x**2), x)',
    'integrate(1/sqrt(x*(sqrt(4*x)+1)**10), x)',
    'integrate(sin(acos(x)), (x, 0, 1))',
    'integrate(log(1/x), (x, 1/4, 1/2))',
    'integrate(1/(1+sin(x)), (x, 0, pi/2))',
    'integrate(sqrt(x)/(sqrt(2012-x)+sqrt(x)), (x, 1, 2011))',
    'integrate((x-1)/((x+1)*sqrt(x**3+x**2+x)), x)',
    'integrate((x**4+4*x**3+6*x**2+4*x+1)/(x**3-3*x**2+3*x-1), (x, -1, 0))',
    'integrate((cos(x)*log(x)+sin(x))/x, x)',
    'integrate(1/(x**3-x), x)',
    'integrate(x*asin(x)/sqrt(1-x**2), (x, 0, 1/2))',
    'integrate(x*(1-x)**99, (x, 0, 1))',
    'integrate(sin(4*x)/sin(x), (x, 0, pi/2))',
    'integrate((x-1)**2/(1+x**(1/3)), x)',
    'integrate(sqrt(2*x**2-1), x)',
    'integrate(sqrt(e**x-1), x)',
    'integrate(x/(x**4+4), x)',
    'integrate((cos(x)-sin(x))**2, (x, 0, 2))',
    'integrate(x*cosh(x)/sinh(x)**2, x)',
    'integrate(x**5/sqrt(1+x**3), (x, 0, 2))',
    'integrate((x**7-1)*log(x), (x, 0, 1))',
    'integrate(log(x**2)-2*log(2*x), x)',
    'integrate(e**(Abs(x)), (x, -1, 3))',
    'integrate((log(x)*cos(x)-sin(x)/x)/(log(x)**2), x)',
    'integrate(x**3-3*x**2+3*x-1, (x, 1, 11))',
    'integrate(12-3*x**2, (x, 0, 2))',
    'integrate(x+(x-3)/(7+sin(x-3)), (x, 0, 6))',
    'integrate((x**5-x**3+x**2-1)/(x**4-x**3+x-1), x)',
    'integrate(log(x), (x, 0, 1))',
    'integrate(1-e**(-x), x)',
    'integrate(sin(x)**2*cos(x)**2, (x, 0, pi))',
    'integrate(pi*sin(pi*sqrt(x))/sqrt(x), (x, 0, 441))',
    'integrate(tan(x)**2, x)',
    'integrate((x-b)**2, (x, 0, 256))',
    'integrate(e**(2*sqrt(x)), x)',
    'integrate(cos(x)*cot(x), x)',
    'integrate(2*log(x)+log(x)**2, x)',
    'integrate(sin(x)*log(sin(x)), x)',
    'integrate(x/(1-x**4), x)',
    'integrate(sec(x)**5*tan(x)**3, x)',
    'integrate(1/(1-sin(x)), (x, -pi/4, pi/4))',
    'integrate(x/sqrt(x**2-2), x)',
]
